<span class='note'><i>Make me look good.</i> Click on the cell below and press <kbd>Ctrl</kbd>+<kbd>Enter</kbd>.</span>

In [1]:
from IPython.core.display import HTML
HTML(open('css/custom.css', 'r').read())

<h5 class='prehead'>SM286D &middot; Introduction to Applied Mathematics with Python &middot; Spring 2020 &middot; Uhan</h5>

<h5 class='lesson'>Lesson 11.</h5>

<h1 class='lesson_title'>Matrix algebra with Python</h1>

## This lesson...

- Matrix algebra with NumPy

---

## What is NumPy?

- __NumPy__ is the fundamental scientific computing package for Python.

- Numerous scientific and mathematical packages for Python use NumPy, including __pandas__ (data analysis and wrangling) and __scikit-learn__ (machine learning).

- Let's start by importing NumPy:

In [2]:
import numpy as np

---

## NumPy arrays

- The main data structure in NumPy is the __array__. Arrays are typically used to represent matrices.

- We can create a one-dimensional array like this:

In [3]:
# Create one-dimensional array
a = np.array([2, 3, 4])

# Print the array
print(a)

# Check the type of the array
print(type(a))

[2 3 4]
<class 'numpy.ndarray'>


- Similarly, we can create a two-dimensional array like this:

In [4]:
# Create two-dimensional array
b = np.array([[1, 2], [3, 4]])

# Print the array
print(b)

# Check the type of the array
print(type(b))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


- We can access and change values of an array like this:

In [5]:
# Print element of a
print(a[1])

# Change element of a
a[2] = 0
print(a)

3
[2 3 0]


In [6]:
# Print element of b
print(b[1, 0])

# Change element of b
b[0, 1] = 100
print(b)

3
[[  1 100]
 [  3   4]]


---

## Some basic Numpy array methods and attributes

- NumPy arrays have a number of useful methods and attributes.

- Learn about some of the more common of these methods by answering the questions below.

- If you're stuck or have doubts, [try searching the documentation.](https://docs.scipy.org/doc/numpy/index.html) 
    - Wading through the documentation can be hard at first but you'll get better at reading documentation with practice. 

### Question 1

Run the code below. What does `np.arange` do? 

In [7]:
c = np.arange(1, 4)
print(c)

[1 2 3]


__Write your answer here. Double-click to edit.__

- `np.arange(start, stop)` produces a one-dimensional array, with values starting at `start`, increasing by 1, and ending at `stop - 1`.

- [Documentation for `np.arange`](https://numpy.org/devdocs/reference/generated/numpy.arange.html)

### Question 2

Run the code below. What does `np.eye` do?

In [8]:
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


__Write your answer here. Double-click to edit.__

- `np.eye(n)` produces a two-dimensional array with `n` rows and columns, with ones on the diagonal and zeros elsewhere (in other words, the identity matrix of size `n`).

- [Documentation for `np.eye`](https://numpy.org/devdocs/reference/generated/numpy.eye.html)

### Question 3

Run the code below. What does `np.zeros()` do?

In [9]:
d = np.zeros((8,2))
print(d)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


__Write your answer here. Double-click to edit.__

- `np.zeros((a, b))` produces a two-dimensional array of zeros with `a` rows and `b` columns.

- [Documentation for `np.zeros`](https://numpy.org/devdocs/reference/generated/numpy.zeros.html)

### Question 4

Run the code below. `.transpose()` is a NumPy array method. What does `.transpose()` do? Does `.transpose()` change the array permanently?

In [10]:
print(d.transpose())
print(d)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


__Write your answer here. Double-click to edit.__

- `.transpose()` takes the transpose of the associated array. It does not change the array permanently.

- [Documentation for `.transpose()`](https://numpy.org/devdocs/reference/generated/numpy.ndarray.transpose.html)

### Question 5

Run the code below. `.shape` is a NumPy array attribute. What information does `.shape` give?

In [11]:
print(d.shape)
print(d.transpose().shape)

(8, 2)
(2, 8)


__Write your answer here. Double-click to edit.__

- For a two-dimensional array, `.shape` contains a tuple `(a, b)` where `a` is the number of rows, and `b` is the number of columns.

- [Documentation for `.shape`](https://numpy.org/devdocs/reference/generated/numpy.ndarray.shape.html)

### Question 6

Run the code below. `.reshape()` is a NumPy array method. What does the `.reshape()` method do? Does `.reshape()` change the array permanently?

In [12]:
e = np.arange(1, 17)
print(e)

f = e.reshape(2, 8)
print(f)

g = e.reshape(4, 4)
print(g)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


__Write your answer here. Double-click to edit.__

- `.reshape(a, b)` takes the entries of the associated array, and puts them back, row-by-row, into an array with `a` rows and `b` columns.

- [Documentation for `.reshape`](https://numpy.org/devdocs/reference/generated/numpy.ndarray.reshape.html)

### Question 7

Run the code below. What does `np.linspace()` do?

In [13]:
h = np.linspace(1, 10, 5)
print(h)

[ 1.    3.25  5.5   7.75 10.  ]


__Write your answer here. Double-click to edit.__

- `np.linspace(start, stop, num)` returns an array of `num` evenly-spaced values between `start` and `stop`.

- [Documentation for `np.linspace`](https://numpy.org/devdocs/reference/generated/numpy.linspace.html)

---

## Matrix multiplication with NumPy arrays

- As you might expect, you can perform various matrix algebra tasks using NumPy arrays.

- Let's start with matrix multiplication.

- Let

$$
A = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}
\qquad
B = \begin{bmatrix}
2\\
0\\
1
\end{bmatrix}
$$


- Let's define these matrices as NumPy arrays:

In [14]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[2], [0], [1]])

print(A)
print(B)

[[1 2 3]
 [4 5 6]]
[[2]
 [0]
 [1]]


- Here's one way to get $AB$:

In [15]:
print(A @ B)

[[ 5]
 [14]]


- Here's another way to get $AB$:

In [16]:
print(A.dot(B))

[[ 5]
 [14]]


- Here's yet another way to get $AB$:

In [17]:
print(np.matmul(A, B))

[[ 5]
 [14]]


- Here's one way __not__ to get $AB$:

In [18]:
print(A * B)

ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 

- Note that `*` does __not__ perform matrix multiplication!

- Continue your exploration of how to use NumPy arrays by answering the questions below.

### Question 8

Run the code cell below. What does `*` do to an array when used with a scalar value?

In [19]:
twoi = 2 * np.eye(3)
print(twoi)

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]


__Write your answer here. Double-click to edit.__

- `*` acts as a scalar multiplication operator when used with a scalar and an array.

### Question 9

Run the code cell below. How do you add arrays with the same dimensions?

In [20]:
threei = twoi + np.eye(3)
print(threei)

[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]]


__Write your answer here. Double-click to edit.__

- The `+` operator adds two arrays together.

---

## Determinants and inverses

- Next, let's explore how to compute determinants and inverses with NumPy arrays.

- Let $C = \begin{bmatrix} 1 & 2 \\ 4 & 5 \end{bmatrix}$:

In [21]:
C = np.array([[1, 2], [4, 5]])

- We can find $\det(C)$ like this:

In [22]:
print(np.linalg.det(C))

-2.9999999999999996


- We can find $C^{-1}$ like this:

In [23]:
print(np.linalg.inv(C))

[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


### Question 10

Write code to compute $C C^{-1}$ using NumPy. Before you run your code, what do you expect to get? Now run your code. Did you get what you expected?

In [24]:
C @ np.linalg.inv(C)

array([[1.00000000e+00, 0.00000000e+00],
       [2.22044605e-16, 1.00000000e+00]])

---

## Solving a system of linear equations

- Consider the system $Cx = d$, where

$$
C = \begin{bmatrix} 1 & 2 \\ 4 & 5 \end{bmatrix} \qquad d = \begin{bmatrix} 5 \\ 14 \end{bmatrix}
$$


### Question 11

Solve for $x$ by computing $C^{-1} d$.

In [25]:
d = np.array([[5], [14]])
x = np.linalg.inv(C) @ d
print(x)

[[1.]
 [2.]]


- You can also use `np.linalg.solve` like this:

In [26]:
# Solve Cx = d
x = np.linalg.solve(C, d)
print(x)

[[1.]
 [2.]]


---

## Eigenvalues and eigenvectors

- Next, let's compute the eigenvalues and eigenvectors of $C$:

In [27]:
# Note that np.linalg.eig returns 2 objects
w, V = np.linalg.eig(C)

print(f"The eigenvalues of C are {w}.\n")
print(f"The eigenvectors of C are the column vectors of")
print(V)

The eigenvalues of C are [-0.46410162  6.46410162].

The eigenvectors of C are the column vectors of
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


- Note that `np.linalg.eig` returns a tuple of 2 objects: `w` and `V`
    - The first object `w` is a one-dimensional array of the eigenvalues. The eigenvalues are repeated according to their multiplicity.
    - The second object `V` is a two-dimensional array of the eigenvectors: the $i$th column of `V` corresponds to the $i$th eigenvalue in `w`.

- [Here is the documentation for `numpy.linalg.eig`.](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.eig.html?highlight=eig)

- To get a column of a two-dimensional array, we can slice the array like this:

In [28]:
# Get the first column of the eigenvector matrix
v0 = V[:, 0]
print(f"The eigenvector corresponding to {w[0]} is")
print(v0)

# Get the second column of the eigenvector matrix
v1 = V[:, 1]
print(f"\nThe eigenvector corresponding to {w[1]} is")
print(v1)

The eigenvector corresponding to -0.4641016151377544 is
[-0.80689822  0.59069049]

The eigenvector corresponding to 6.464101615137754 is
[-0.34372377 -0.9390708 ]


### Question 12

Check if `v0` defined in the above code cell is in fact an eigenvector of $C$: compute $C v_0$ and $w_0 v_0$, and check if they are equal.

In [29]:
print("C v0 is")
print(C @ v0)

print("\nw0 v0 is")
print(w[0] * v0)

C v0 is
[ 0.37448277 -0.27414041]

w0 v0 is
[ 0.37448277 -0.27414041]


### Question 13

Find the eigenvalues and eigenvectors of the matrix $\displaystyle{\begin{bmatrix} 0 & 0 & 2 \\ -2 & 1 & 4 \\ -1 & 0 & 3 \end{bmatrix}}$. Can you find eigenvectors with integer entries? 

In [30]:
# Define the matrix as a NumPy array
E = np.array([[0, 0, 2], [-2, 1, 4], [-1, 0, 3]])

# Find the eigenvalues and eigenvectors of E
w, V = np.linalg.eig(E)

# Print the eigenvalues
print("The eigenvalues of this matrix are")
print(w)

# Print the eigenvectors
print("\nThe eigenvectors of this matrix are the column vectors of")
print(V)

The eigenvalues of this matrix are
[1. 1. 2.]

The eigenvectors of this matrix are the column vectors of
[[ 0.         -0.89442719 -0.40824829]
 [ 1.          0.         -0.81649658]
 [ 0.         -0.4472136  -0.40824829]]


- The next code cell factors the matrix $C$ into a product of the form $V D V^{-1}$, where
    - $V$ is a matrix whose columns are the eigenvectors $v_0$ and $v_1$ of $C$ (i.e. the second output from `np.linalg.eig(C)`)
    - $D$ is a diagonal matrix whose entries are the eigenvalues $w_0$ and $w_1$ of $C$ (i.e. the first output from `np.linalg.eig(C)`)

- In other words, we can factor $C$ like this:
\begin{equation*}
C = \begin{bmatrix} \mid & \mid \\ v_0 & v_1 \\ \mid & \mid \end{bmatrix}\; \begin{bmatrix} w_0 & 0 \\ 0 & w_1 \end{bmatrix} \; 
\begin{bmatrix} \mid & \mid \\ v_0 & v_1 \\ \mid & \mid \end{bmatrix}^{-1}.
\end{equation*}

In [31]:
# Find the eigenvalues and eigenvectors of C
w, V = np.linalg.eig(C)

# np.diag takes a one-dimensional array and makes it into a diagonal matrix
D = np.diag(w)
print(D)

# C should be equal to V * D * V^-1
print(V @ D @ np.linalg.inv(V))
print(C)

[[-0.46410162  0.        ]
 [ 0.          6.46410162]]
[[1. 2.]
 [4. 5.]]
[[1 2]
 [4 5]]


### Question 14

Factor the matrix from Question 13 as a product of the form $VDV^{-1}$, where $D$ is a diagonal matrix.

In [32]:
# Find the eigenvalues and eigenvectors of E, the matrix from Question
w, V = np.linalg.eig(E)

# np.diag takes a one-dimensional array and makes it into a diagonal matrix
D = np.diag(w)
print(D)

# C should be equal to V * D * V^-1
print(V @ D @ np.linalg.inv(V))
print(E)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]]
[[-9.91130574e-17  0.00000000e+00  2.00000000e+00]
 [-2.00000000e+00  1.00000000e+00  4.00000000e+00]
 [-1.00000000e+00  0.00000000e+00  3.00000000e+00]]
[[ 0  0  2]
 [-2  1  4]
 [-1  0  3]]


---

## Where is the RREF?

__WARNING. The material in this section is much more advanced than the rest of the material in this lesson. We recommend skipping this section on a first pass, only coming back to it if you have extra time.__

Now you might be interested in finding the row reduced echelon form (RREF) for a matrix; after all, that was the main tool in SM261 and we used it extensively to perform all sorts of computations. However, there is no such command in NumPy and there is a good reason for its absence. It turns out that row reduction is numerically unstable: small changes in the entries of a matrix can cause qualitative changes in its row reduction. 

Fortunately, almost every sensible application of row reduction can be accomplished by a numerically stable operation called the __singular value decomposition (SVD)__. The SVD of a $m \times n$ matrix $C$ is a factorization, 

$$
C = U\Sigma V^T,
$$ 

where $U$ and $V$ are orthonormal matrices (the dot product of the columns of these matrices are zero if the columns are different and 1 if the columns are equal) of sizes $m \times m$ and $n \times n$, respectively, and $\Sigma$ is a block matrix whose upper left corner is a square diagonal matrix with nonzero entries on the diagonal and all other blocks are zero. The number of nonzero entries of $\Sigma$ is the rank $r$ of $C$. To be explicit, 

$$
\Sigma = \begin{bmatrix} \Sigma & 0 \\ 0 & 0  \end{bmatrix},
$$ 

where the matrix $\Sigma$ is an $r\times r$ diagonal matrix, the zero to its right is a $r \times (n-r)$ matrix, and the zero in the bottom corner is an $(m-r) \times (n-r)$ matrix. 

As an example, consider the matrix 

$$
C =  \begin{bmatrix} \phantom{-}1 & -1 \\ -2 & \phantom{-}2 \\ \phantom{-}2 & -2 \end{bmatrix}.
$$ 

The matrix $C$ has rank 1 and has SVD given by:

\begin{equation} \label{svdeq} C = \begin{bmatrix} \phantom{-}1/3  & \phantom{-}2/\sqrt{5} & -2/\sqrt{45} \\
-2/3 & \phantom{-}1/\sqrt{5} & \phantom{-}4/\sqrt{45} \\ \phantom{-}2/3 & \phantom{-}0 & \phantom{-}5/\sqrt{45} \end{bmatrix} \, \begin{bmatrix} 3/\sqrt{2} & 0 \\ 0 & 0 \\ 0 & 0  \end{bmatrix} \, \begin{bmatrix} 1/\sqrt{2} & -1/\sqrt{2} \\ 1/\sqrt{2} & \phantom{-}1/\sqrt{2} \end{bmatrix}.\end{equation} 

Note that $C$ is a $3 \times 2$ matrix, $U$ is $3 \times 3$ and $V$ is $2 \times 2$. 

We can recover four critical subspaces of $C$ by writing the SVD factorization in the following form

$$
C = \begin{bmatrix} U_r & U_{r,\perp} \end{bmatrix} \begin{bmatrix} S_r & 0 \\ 0 & 0 \end{bmatrix} \begin{bmatrix} V_r^T \\ V_{r,\perp}^T \end{bmatrix},
$$

where $S_r$ is an $r \times r$ diagonal matrix with nonzero entries on the diagonal. Then 

$$ 
\begin{array}{rll} \text{range}(C) & = & \text{range}(U_r), \\
\text{null}(C) & = & \text{range}(V_{r,\perp}), \\
\text{range}(C^T) & = & \text{range}(V_r), \\
\text{null}(C^T) & = & \text{range}(U_{r,\perp}). \end{array}
$$ 

Recalling that the range of a matrix is the span of its columns, this gives us a way to describe each of the four key subspaces associated to a matrix $C$. Indeed, since the matrices $U$ and $V$ are orthonormal, their columns and rows form a basis for the space that they span. 

Let's see how some of these ideas work for our SVD of $C$. There is just one nonzero element in $\Sigma$, so $C$ must have rank 1. Then $U_r$ should be $3 \times 1$ ($U_r$ has $r$ columns). So a basis for the range of $C$ is the set consisting of the first column vector in $U$: 

$$
\displaystyle{\left\{\begin{bmatrix} \phantom{-}1/3 \\ -2/3 \\ \phantom{-}2/3 \end{bmatrix} \right\}}.
$$

Check that this really is the range of $C$! The null space of $C$ is the range of the matrix $V_{r,\perp}$. The matrix $V_r^T$ is an $r \times n$ matrix (has $r$ __rows__), meaning that the matrix $V_{r,\perp}^T$ has size $(n-r)$ rows. That means that $V_{r,\perp}$ has $n-r$ columns, each the transpose of one of the last $n-r$ rows of $V_{r,\perp}^T$. Now 

$$
\begin{bmatrix} V_{r}^T \\ V_{r,\perp}^T \end{bmatrix} = \begin{bmatrix} 1/\sqrt{2} & -1/\sqrt{2} \\ 1/\sqrt{2} & \phantom{-}1/\sqrt{2} \end{bmatrix}
$$ 

so $V_{r,\perp}^T  = \begin{bmatrix} 1/\sqrt{2} & \phantom{-}1/\sqrt{2} \end{bmatrix}$ and $V_{r,\perp} = \begin{bmatrix} 1/\sqrt{2} \\ 1/\sqrt{2} \end{bmatrix}$. A basis for the null space of $C$ is 

$$
\left\{  \begin{bmatrix} 1/\sqrt{2} \\ 1/\sqrt{2} \end{bmatrix} \right\}
$$. 

Check that this is true!  

In the next code cell we compute the Singular Value Decomposition (SVD) of the matrix $C$. Note that on line 14 we learn that `vh`, the third output of `np.linalg.svd`, is already transposed: `vh` = $V^T$.

In [33]:
# Define a test matrix P
P = np.array([[1, 2, 3], [3, 2, 1], [1, 1, 1]])

# Find the SVD of P
u, s, vh = np.linalg.svd(P)

print("The matrix U is")
print(u)

print("\nThe matrix Sigma is")
print(s)

print("\nThe matrix V^T is")
print(vh)

# Check the factorization: this should equal P
print("\nMultiplying these together, we should get back P:")
print(u @ np.diag(s) @ vh)

The matrix U is
[[-6.66666667e-01  7.07106781e-01 -2.35702260e-01]
 [-6.66666667e-01 -7.07106781e-01 -2.35702260e-01]
 [-3.33333333e-01  2.77555756e-17  9.42809042e-01]]

The matrix Sigma is
[5.19615242e+00 2.00000000e+00 5.71440190e-17]

The matrix V^T is
[[-5.77350269e-01 -5.77350269e-01 -5.77350269e-01]
 [-7.07106781e-01  5.55111512e-17  7.07106781e-01]
 [ 4.08248290e-01 -8.16496581e-01  4.08248290e-01]]

Multiplying these together, we should get back P:
[[1. 2. 3.]
 [3. 2. 1.]
 [1. 1. 1.]]


### Question 15

(a) Compute the SVD of the matrix 

$$
Q = \begin{bmatrix} 2 & 1 & 0  &1 & 0 \\
 1 & 0 & 1 & 1 & 1 \\
  -1 & 1 & 1 & 0 & 1 \\
  2 & 2 & 2 & 2 & 2 \end{bmatrix}.
$$

(b) Verify that the rank $r$ of the matrix $Q$ is 3 using its SVD. 

(c) Find the shapes of the matrices $U$, $S$ and $V^T$.

__The next three parts of this question are considered challenge material.__

(d) The first $r$ columns of $U$ make up $U_r$ and the remaining columns make up $U_{r,\perp}$. The first $r$ rows of $V^T$ make up $V_{r}^T$ and the remaining rows make up $V_{r,\perp}^T$. Find these submatrices.

(e) Find a basis for the null space of the original matrix $Q$. Does this basis have the correct number of vectors? Do your vectors live in the correct ambient space? 

(f) Find a basis for the range of the original matrix $Q$. Does this basis have the correct number of vectors? Do your vectors live in the correct ambient space?

In [34]:
# Define the matrix
Q = np.array([[2, 1, 0, 1, 0], [1, 0, 1, 1, 1], [-1, 1, 1, 0, 1], [2, 2, 2, 2, 2]])

# (a) Find SVD of Q
u, s, vh = np.linalg.svd(Q)

print("The matrix U is")
print(u)

print("\nThe matrix Sigma is")
print(s)

print("\nThe matrix V^T is")
print(vh)

The matrix U is
[[-0.36206122  0.6246702   0.47822465 -0.5       ]
 [-0.34561768  0.00735298 -0.79403674 -0.5       ]
 [-0.14568802 -0.7687844   0.37114088 -0.5       ]
 [-0.85336692 -0.13676122  0.05532879  0.5       ]]

The matrix Sigma is
[5.22657769e+00 2.34830781e+00 1.08089598e+00 2.05437465e-16]

The matrix V^T is
[[-5.03347715e-01 -4.23696576e-01 -4.20550437e-01 -4.61949076e-01
  -4.20550437e-01]
 [ 7.46050124e-01 -1.77845780e-01 -4.40723250e-01  1.52663437e-01
  -4.40723250e-01]
 [-9.07309675e-02  8.88173457e-01 -2.88869869e-01 -1.89800418e-01
  -2.88869869e-01]
 [-3.71938085e-01  2.08166817e-16  1.59820875e-01  7.43876170e-01
  -5.31758960e-01]
 [-2.08519166e-01  6.24500451e-17 -7.21049120e-01  4.17038332e-01
   5.12529954e-01]]


(b) The matrix $\Sigma$ (the array `s`) has 3 nonzero entries, so the rank of $Q$ is 3. (Note the last entry of `s` is on the order of magnitude of $10^{-16}$: it is effectively zero.)

In [35]:
# (c) Shapes of SVD factors
print(f"Shape of U: {u.shape}")
print(f"Shape of Sigma: {s.shape}")
print(f"Shape of V^T: {vh.shape}")

Shape of U: (4, 4)
Shape of Sigma: (4,)
Shape of V^T: (5, 5)


In [36]:
# (d) Submatrices
r = 3  # rank of Q
ur = u[:, :r]
urperp = u[:, r:]
vhr = vh[:r, :]
vhrperp = vh[r:, :]

print("The matrix U_r is")
print(ur)

print("\nThe matrix U_{r, perp} is")
print(urperp)

print("\nThe matrix V_r^T is")
print(vhr)

print("\nThe matrix V_{r, perp}^T is")
print(vhrperp)

The matrix U_r is
[[-0.36206122  0.6246702   0.47822465]
 [-0.34561768  0.00735298 -0.79403674]
 [-0.14568802 -0.7687844   0.37114088]
 [-0.85336692 -0.13676122  0.05532879]]

The matrix U_{r, perp} is
[[-0.5]
 [-0.5]
 [-0.5]
 [ 0.5]]

The matrix V_r^T is
[[-0.50334771 -0.42369658 -0.42055044 -0.46194908 -0.42055044]
 [ 0.74605012 -0.17784578 -0.44072325  0.15266344 -0.44072325]
 [-0.09073097  0.88817346 -0.28886987 -0.18980042 -0.28886987]]

The matrix V_{r, perp}^T is
[[-3.71938085e-01  2.08166817e-16  1.59820875e-01  7.43876170e-01
  -5.31758960e-01]
 [-2.08519166e-01  6.24500451e-17 -7.21049120e-01  4.17038332e-01
   5.12529954e-01]]


(e) From the discussion above, we know that $\text{null}(Q) = \text{range}(V_{r,\perp})$. We computed $V_{r,\perp}^T$ in part (d), which has 2 rows. So, $\text{null}(Q)$ is the span of these 2 row vectors, which live in $\mathbb{R}^5$.

(f) From the discussion above, we know that $\text{range}(Q) = \text{range}(U_r)$. We computed $U_r$ in part (d), which has 3 columns. So, $\text{range}(U_r)$ is the span of these 3 column vectors, which live in $\mathbb{R}^4$.